### PR TITLE
Add a Code of Conduct

### PR DESCRIPTION
**Pull request by mlinksva**
I think given some of setting up of the project, it should lead by
example, and "ship" with a CoC. I have in mind particularly the
sentence:

> Many people use and produce bits of free knowledge but any serious
> attempt quickly runs into tremendous barriers, in every field.
> Participants receive unequal welcome due to gender, language,
> cultural or economic differences.

Using a pull request in case anyone wishes to cheer or object.

### CODE REVIEW

**Comment by hellekin** [comment]
I'm against adopting a code of conduct, especially one that distinguishes arbitrary categories whose list could grow indefinitely.  I don't need a code of conduct to be civil, and I expect other contributors to be mature and not a bunch of idiots who require a code of conduct to behave.

**Comment by mlinksva** [comment]
@hellekin the categories are not arbitrary, but based on experience which your expectation does not acknowledge.

I'm very mildly surprised, given http://book.costoffreedom.cc/book/opening:freedom/free-as-in-commons.html

Would be curious whether you reject the [parallels](https://www.harihareswara.net/sumana/2016/02/19/0) and why.

**Comment by hellekin** [comment]
I don't understand what you mean by "parallels".  The article you linked doesn't mention the term.

I'm sure CoC are based on experience.  I'm just convinced they say obvious things, and use categories that I don't necessarily approve.  I like the category "human", anything more "fine-grained" is fragmenting IMO.

**Comment by mlinksva** [comment]
I should've been more clear: the parallels between copyleft (which you wrote about in "free as in commons") and codes of conduct (the 2nd link discusses both).

Have you read the CoC I proposed? It does not carve out protected classes. See **everyone**.

On the theme of this book, what are the costs you perceive? Do you believe those costs outweigh any cost reduction caused by a CoC serving to deter predators, and/or do you believe a CoC, this one in particular, cannot possibly have such an effect? (I'd love to see data in any direction, of course.)

**Comment by hellekin** [comment]
On 04/26/2016 05:01 PM, Mike Linksvayer wrote:

> I should've been more clear: the parallels between copyleft (which you wrote
> about in "free as in commons") and codes of conduct (the 2nd link
> discusses
> both).

I don't share at all this perspective.  Copyleft licenses are made to
revert the restrictive effect of Copyright law and grant users rights
within the scope of that law.  A Code of Conduct is a well-wishing moral
compass to tell bullies that they shouldn't do what they're doing.

The author wrote: "I strongly suspect I'll be harassed if they know I'm
a woman, and that I don't have any reason to believe I can avoid or
usefully complain about that harassment, how free am I to participate in
that community?"

So her goal is to implement a way for victims of harassment to "avoid or
usefully complain".  I see that as completely orthogonal to a CoC.
Communication channels and community support should be clear, but asking
bullies to stop being bullies is hopeless.

> Have you read the CoC I proposed?

This is what prompted me to intervene in this issue.

> It does not carve out protected classes. See **everyone**.

It mentions: "a harassment-free experience for everyone, regardless of
age, body size, disability, ethnicity, gender identity and expression,
level of experience, nationality, personal appearance, race, religion,
or sexual identity and orientation."

It doesn't mention "poor use of English, religious and spiritual values,
purchasing power, political orientation, nutritional preference, bad
smell, contagious diseases, etc."

Actually I'm starting thinking that comparing the GPL and a CoC on the
ground of an alleged "theory of change" is missing the point that the
GPL and a CoC (or _this_ code of conduct) are antinomic: the subject in
the GPL is "anyone, for any purpose", which is by scope the most
inclusive.  The CoC seems to excuse the community for harboring diversity.

The CoC tells the bullies: we know you're here, and please, don't do
what you do.  It tells the (potential) victims: here, in this community,
you can assert your identity and be bullied, but don't worry, we'll take
take of the bullies.  I don't think a CoC is necessary for that.
Confronting the bullies is.  Whether you have a CoC or not won't stop
them, and expressing the limits by stigmatizing the very characteristics
you want to blur doesn't sound too effective.

> On the theme of this book, what are the costs you perceive?
> Do you believe those costs outweigh any cost reduction caused by a CoC
> serving to deter predators, and/or do you believe a CoC, this one in
> particular, cannot possibly have such an effect? (I'd love to see data in
> any direction, of course.)

I don't perceive it in terms of cost, but in terms of assertion.  I
don't believe a CoC has any deterrent power.  I don't believe you can
reduce human relationships and interactions to "data", so you won't see
any.  I hope my position is clearer now.

In the second part, the CoC mentions:

"Examples of behavior that contributes to creating a positive
environment include:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members"

This is positive, as it shows what is expected from participants.  All
the threats over project management and such are counter-productive.  It
very much sounds like a fruit of the U.S. of A. fear of legal action.
If that's the case, better make a legal statement and say that whatever
is said that doesn't match the standard of civility may be edited,
deleted, and further punitive action may be pursued against the
culprits, including permanent ban from the community or penal action if
necessary.

Now, inviting people to report aggression is empathetic but given how
victims tend to be isolated, it's not enough to give an email--stopping
there would be to wash oneself from the responsibility of actively
seeking a sane community.  I'm not _fundamentally_ against a CoC, but I
feel it's like a last resort move when everything else failed.  This one
is particularly defensive and not so assertive about what's wanted, vs.
what the Grinch will do if you behave like a jerk.

# 

hk

## 

 _ _     We are free to share code and we code to share freedom
(_X_)yne Foundation, Free Culture Foundry \* https://www.dyne.org/donate/

**Comment by hellekin** [comment]
On 05/12/2016 02:18 AM, Jon Phillips wrote:

> Merged #58.

That's it?  Discussion over?

# 

hk

## 

 _ _     We are free to share code and we code to share freedom
(_X_)yne Foundation, Free Culture Foundry \* https://www.dyne.org/donate/

**Pull request merged**
